version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=ctf
    networks:
      - juicenet

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: juiceshop
      MYSQL_USER: juiceuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - juicenet
    secrets:
      - db_root_password
      - db_password

networks:
  juicenet:

volumes:
  mysql-data:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
